
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'

- script: ng test --browsers=ChromeHeadless --watch=false
  displayName: 'Run unit Tests'

- script: ng build --prod
  displayName: 'ng build'